version: "3.9" # optional since v1.27.0
# description: "A short description of the role"
services:
  db:
    image: postgres
    container_name: docker_test_db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}